[common]
callsign = "Magic"
# One of "Blue", or "Red"
coalition = "Blue"

[tacview]
host = "example.com"
port = 42674
username = "magic-bot"
#password = ""

[srs]
host = "example.com"
port = 5002
username = "Magic Bot"
# One of "Spectator", "Blue", or "Red"
coalition = "Blue"
frequency = 136000000

[openai]
api_key = "OPENAI_API_KEY"
# Available voices: https://platform.openai.com/docs/guides/text-to-speech/voice-options
speech_voice = "alloy"
speech_speed = 1.0
